// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tehnicharche.Data;

#nullable disable

namespace Tehnicharche.Data.Migrations
{
    [DbContext(typeof(TehnicharcheDbContext))]
    [Migration("20260216193809_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCURRENCY_STAMP_1",
                            Email = "ivan@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "IVAN@EXAMPLE.COM",
                            NormalizedUserName = "IVAN.TECH",
                            PasswordHash = "AQAAAAIAAYagAAAAEMockHashValueForDevOnlyUser1==",
                            PhoneNumber = "+359888123001",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "SECURITY_STAMP_1",
                            TwoFactorEnabled = false,
                            UserName = "ivan.tech"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCURRENCY_STAMP_2",
                            Email = "maria@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MARIA@EXAMPLE.COM",
                            NormalizedUserName = "MARIA.REPAIRS",
                            PasswordHash = "AQAAAAIAAYagAAAAEMockHashValueForDevOnlyUser2==",
                            PhoneNumber = "+359888456002",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "SECURITY_STAMP_2",
                            TwoFactorEnabled = false,
                            UserName = "maria.repairs"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCURRENCY_STAMP_3",
                            Email = "plovdiv@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PLOVDIV@EXAMPLE.COM",
                            NormalizedUserName = "PLOVDIV.FIXIT",
                            PasswordHash = "AQAAAAIAAYagAAAAEMockHashValueForDevOnlyUser3==",
                            PhoneNumber = "+359888789003",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "SECURITY_STAMP_3",
                            TwoFactorEnabled = false,
                            UserName = "plovdiv.fixit"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000004",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCURRENCY_STAMP_4",
                            Email = "stz@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STZ@EXAMPLE.COM",
                            NormalizedUserName = "STZ.ELECTRIC",
                            PasswordHash = "AQAAAAIAAYagAAAAEMockHashValueForDevOnlyUser4==",
                            PhoneNumber = "+359888321004",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "SECURITY_STAMP_4",
                            TwoFactorEnabled = false,
                            UserName = "stz.electric"
                        });
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics Repair"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Appliance Repair"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Soldering & PCB Assembly"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Computer Repair"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mobile Phone Repair"
                        },
                        new
                        {
                            Id = 6,
                            Name = "TV & Audio Repair"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Home Wiring & Electrical"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Handyman (general technical)"
                        },
                        new
                        {
                            Id = 9,
                            Name = "3D Printing & Prototyping"
                        });
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Blagoevgrad",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bansko",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sandanski",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Burgas",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Nesebar",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sozopol",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Varna",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Provadiya",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Veliko Tarnovo",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gorna Oryahovitsa",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 11,
                            Name = "Vidin",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 12,
                            Name = "Vratsa",
                            RegionId = 6
                        },
                        new
                        {
                            Id = 13,
                            Name = "Gabrovo",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 14,
                            Name = "Dobrich",
                            RegionId = 8
                        },
                        new
                        {
                            Id = 15,
                            Name = "Balchik",
                            RegionId = 8
                        },
                        new
                        {
                            Id = 16,
                            Name = "Kardzhali",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 17,
                            Name = "Kyustendil",
                            RegionId = 10
                        },
                        new
                        {
                            Id = 18,
                            Name = "Lovech",
                            RegionId = 11
                        },
                        new
                        {
                            Id = 19,
                            Name = "Montana",
                            RegionId = 12
                        },
                        new
                        {
                            Id = 20,
                            Name = "Pazardzhik",
                            RegionId = 13
                        },
                        new
                        {
                            Id = 21,
                            Name = "Pernik",
                            RegionId = 14
                        },
                        new
                        {
                            Id = 22,
                            Name = "Pleven",
                            RegionId = 15
                        },
                        new
                        {
                            Id = 23,
                            Name = "Plovdiv",
                            RegionId = 16
                        },
                        new
                        {
                            Id = 24,
                            Name = "Asenovgrad",
                            RegionId = 16
                        },
                        new
                        {
                            Id = 25,
                            Name = "Razgrad",
                            RegionId = 17
                        },
                        new
                        {
                            Id = 26,
                            Name = "Ruse",
                            RegionId = 18
                        },
                        new
                        {
                            Id = 27,
                            Name = "Shumen",
                            RegionId = 19
                        },
                        new
                        {
                            Id = 28,
                            Name = "Silistra",
                            RegionId = 20
                        },
                        new
                        {
                            Id = 29,
                            Name = "Sliven",
                            RegionId = 21
                        },
                        new
                        {
                            Id = 30,
                            Name = "Smolyan",
                            RegionId = 22
                        },
                        new
                        {
                            Id = 31,
                            Name = "Sofia",
                            RegionId = 23
                        },
                        new
                        {
                            Id = 32,
                            Name = "Kostinbrod",
                            RegionId = 24
                        },
                        new
                        {
                            Id = 33,
                            Name = "Pirdop",
                            RegionId = 24
                        },
                        new
                        {
                            Id = 34,
                            Name = "Stara Zagora",
                            RegionId = 25
                        },
                        new
                        {
                            Id = 35,
                            Name = "Targovishte",
                            RegionId = 26
                        },
                        new
                        {
                            Id = 36,
                            Name = "Haskovo",
                            RegionId = 27
                        },
                        new
                        {
                            Id = 37,
                            Name = "Yambol",
                            RegionId = 28
                        });
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("RegionId");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CityId = 31,
                            CreatedAt = new DateTime(2025, 11, 1, 11, 30, 0, 0, DateTimeKind.Local),
                            CreatorId = "00000000-0000-0000-0000-000000000001",
                            Description = "Micro-soldering, component replacement, BGA rework (where feasible). 5+ years experience with consumer and industrial PCBs.",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/06/06/16/35/cyber-2377718_1280.jpg",
                            IsDeleted = false,
                            Price = 45.00m,
                            RegionId = 23,
                            Title = "Surface-mount soldering & PCB repair (small boards)"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CityId = 4,
                            CreatedAt = new DateTime(2025, 10, 20, 17, 0, 0, 0, DateTimeKind.Local),
                            CreatorId = "00000000-0000-0000-0000-000000000002",
                            Description = "Fault codes, pump & heater replacement, drum/shaft repair, water inlet and electronic control fixes. Parts quoted separately.",
                            ImageUrl = "https://cdn.pixabay.com/photo/2014/03/06/11/30/washing-machine-280752_1280.jpg",
                            IsDeleted = false,
                            Price = 80.00m,
                            RegionId = 2,
                            Title = "Washing machine diagnostics & repair"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CityId = 23,
                            CreatedAt = new DateTime(2025, 12, 5, 13, 15, 0, 0, DateTimeKind.Local),
                            CreatorId = "00000000-0000-0000-0000-000000000003",
                            Description = "Power rails, damaged connectors, short diagnosis. I repair DC jack, blown MOSFETs, burnt traces and do BGA reballing referrals.",
                            ImageUrl = "https://cdn.pixabay.com/photo/2014/05/06/16/09/imac-338988_1280.jpg",
                            IsDeleted = false,
                            Price = 120.00m,
                            RegionId = 16,
                            Title = "Laptop motherboard repair — diagnostics + component level"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            CityId = 7,
                            CreatedAt = new DateTime(2025, 9, 30, 11, 45, 0, 0, DateTimeKind.Local),
                            CreatorId = "00000000-0000-0000-0000-000000000001",
                            Description = "Original and high-quality aftermarket screens; installation and calibration. Data-safe service — backup recommended before service.",
                            ImageUrl = "https://cdn.pixabay.com/photo/2023/10/19/12/01/technician-8326389_1280.jpg",
                            IsDeleted = false,
                            Price = 60.00m,
                            RegionId = 3,
                            Title = "Mobile phone screen replacement (all makes)"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 7,
                            CityId = 34,
                            CreatedAt = new DateTime(2025, 8, 10, 13, 0, 0, 0, DateTimeKind.Local),
                            CreatorId = "00000000-0000-0000-0000-000000000004",
                            Description = "Safe, certified wiring repairs, new socket installs, LED lighting installation and troubleshooting. I follow local electrical codes.",
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/12/07/10/49/electrician-1080554_1280.jpg",
                            IsDeleted = false,
                            Price = 35.00m,
                            RegionId = 25,
                            Title = "Home electrical — small jobs, sockets, switches, lighting"
                        });
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Blagoevgrad"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Burgas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Varna"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Veliko Tarnovo"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vidin"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Vratsa"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gabrovo"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Dobrich"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Kardzhali"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kyustendil"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Lovech"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Montana"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Pazardzhik"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Pernik"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Pleven"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Plovdiv"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Razgrad"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Ruse"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Shumen"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Silistra"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Sliven"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Smolyan"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Sofia City"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Sofia Province"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Stara Zagora"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Targovishte"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Haskovo"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Yambol"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Tehnicharche.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Tehnicharche.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tehnicharche.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Tehnicharche.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.City", b =>
                {
                    b.HasOne("Tehnicharche.Data.Models.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.Listing", b =>
                {
                    b.HasOne("Tehnicharche.Data.Models.Category", "Category")
                        .WithMany("Listings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tehnicharche.Data.Models.City", "City")
                        .WithMany("Listings")
                        .HasForeignKey("CityId");

                    b.HasOne("Tehnicharche.Data.Models.ApplicationUser", "Creator")
                        .WithMany("Listings")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tehnicharche.Data.Models.Region", "Region")
                        .WithMany("Listings")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("Creator");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.Category", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.City", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.Region", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
