// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tehnicharche.Data;

#nullable disable

namespace Tehnicharche.Data.Migrations
{
    [DbContext(typeof(TehnicharcheDbContext))]
    [Migration("20260214143340_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b1a7f9d6-4e3c-4a1b-9a2b-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d72ed1e0-8dd5-4594-b9c9-07b01016b9fc",
                            Email = "ivan.petrov@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "IVAN.PETROV@EXAMPLE.COM",
                            NormalizedUserName = "IVAN_PETROV",
                            PhoneNumber = "+359887123001",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "753ac267-fabc-4565-8a86-0834cbc6a5fd",
                            TwoFactorEnabled = false,
                            UserName = "ivan_petrov"
                        },
                        new
                        {
                            Id = "c2b8e0a7-5f4d-4b2c-8b3c-222222222222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ce002fc3-0f9f-47ac-830b-f7017c25fb12",
                            Email = "maria.georgieva@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MARIA.GEORGIEVA@EXAMPLE.COM",
                            NormalizedUserName = "MARIA_GEORGIEVA",
                            PhoneNumber = "+359888234567",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c1ac5fa4-d732-4e8f-99e8-aa8c5a2f0557",
                            TwoFactorEnabled = false,
                            UserName = "maria_georgieva"
                        },
                        new
                        {
                            Id = "d3c9f1b8-6a5e-4c3d-9c4d-333333333333",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4ba121e5-5342-4988-87f4-3bce9787e353",
                            Email = "stoyan.tech@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STOYAN.TECH@EXAMPLE.COM",
                            NormalizedUserName = "STOYAN_TECH",
                            PhoneNumber = "+359878345678",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dad00c05-a154-412d-bcbf-d9e3c33ea397",
                            TwoFactorEnabled = false,
                            UserName = "stoyan_tech"
                        },
                        new
                        {
                            Id = "e4d0a2c9-7b6f-4d4e-0d5e-444444444444",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bfbce724-16e8-4852-b5a9-ac3581adec79",
                            Email = "elena.service@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ELENA.SERVICE@EXAMPLE.COM",
                            NormalizedUserName = "ELENASERVICE",
                            PhoneNumber = "+359889456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "00efec15-ad3a-4d50-8945-f22542a13201",
                            TwoFactorEnabled = false,
                            UserName = "elenaservice"
                        },
                        new
                        {
                            Id = "f5e1b3da-8c7g-4e5f-1e6f-555555555555",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6181928c-f1b3-4322-b782-7bf7b8258bb0",
                            Email = "petar.fix@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PETAR.FIX@EXAMPLE.COM",
                            NormalizedUserName = "PETAR_FIX",
                            PhoneNumber = "+359886567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5a21b14b-64ec-4bb7-9588-8cc4590cfd65",
                            TwoFactorEnabled = false,
                            UserName = "petar_fix"
                        },
                        new
                        {
                            Id = "a6f2c4eb-9d8h-4f6g-2f7g-666666666666",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "34c20ba7-7b21-4208-85dc-703cc15bee2a",
                            Email = "radostin.electro@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "RADOSTIN.ELECTRO@EXAMPLE.COM",
                            NormalizedUserName = "RADOSTIN_ELECTRO",
                            PhoneNumber = "+359882678901",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "99a72d3d-acf2-4821-b920-7b5cde3926c9",
                            TwoFactorEnabled = false,
                            UserName = "radostin_electro"
                        });
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Електроника и запояване"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ремонт на домакински уреди"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Електротехника и окабеляване"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ремонт на телефони и таблети"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Монтаж и сглобяване"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Диагностика и сервиз"
                        });
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "София",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Младост",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Пловдив",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Карлово",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Варна",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Бургас",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 7,
                            Name = "Русе",
                            RegionId = 5
                        });
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("RegionId");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CityId = 1,
                            CreatedAt = new DateTime(2025, 1, 10, 11, 0, 0, 0, DateTimeKind.Local),
                            CreatorId = "b1a7f9d6-4e3c-4a1b-9a2b-111111111111",
                            Description = "Запояване на SMD/TH components, подмяна на чипове, ремонт на дистанционни и малки платки. Работя с стационарна станция за запояване и горещ въздух.",
                            ImageUrl = "https://source.unsplash.com/800x450/?soldering,electronics",
                            IsDeleted = false,
                            Price = 35.00m,
                            RegionId = 1,
                            Title = "Запояване на платки и ремонт на дребна електроника"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CityId = 2,
                            CreatedAt = new DateTime(2025, 1, 21, 16, 30, 0, 0, DateTimeKind.Local),
                            CreatorId = "c2b8e0a7-5f4d-4b2c-8b3c-222222222222",
                            Description = "Диагностика за 20 лв, ремонт на помпи, лагер и електроника. Извършвам и монтаж/демонтаж.",
                            ImageUrl = "https://source.unsplash.com/800x450/?washing-machine,repair",
                            IsDeleted = false,
                            Price = 70.00m,
                            RegionId = 1,
                            Title = "Ремонт и диагностика на перални"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CityId = 3,
                            CreatedAt = new DateTime(2025, 2, 1, 10, 15, 0, 0, DateTimeKind.Local),
                            CreatorId = "d3c9f1b8-6a5e-4c3d-9c4d-333333333333",
                            Description = "Монтаж на контакти, ключове и осветление. Гаранция 12 месеца за извършената работа.",
                            ImageUrl = "https://source.unsplash.com/800x450/?electrician,tools",
                            IsDeleted = false,
                            Price = 45.00m,
                            RegionId = 2,
                            Title = "Инсталация и окабеляване за нови контакти"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CityId = 5,
                            CreatedAt = new DateTime(2025, 1, 18, 13, 45, 0, 0, DateTimeKind.Local),
                            CreatorId = "e4d0a2c9-7b6f-4d4e-0d5e-444444444444",
                            Description = "Бърза смяна на дисплей и батерия на повечето марки. Оригинални/следпазарни части по избор.",
                            ImageUrl = "https://source.unsplash.com/800x450/?phone-repair,smartphone",
                            IsDeleted = false,
                            Price = 60.00m,
                            RegionId = 3,
                            Title = "Смяна на дисплей и батерия за смартфони"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CityId = 6,
                            CreatedAt = new DateTime(2025, 1, 5, 12, 0, 0, 0, DateTimeKind.Local),
                            CreatorId = "f5e1b3da-8c7g-4e5f-1e6f-555555555555",
                            Description = "Проверка, смяна на нагревател и термостат. Монтаж и обезвъздушаване.",
                            ImageUrl = "https://source.unsplash.com/800x450/?water-heater,repair",
                            IsDeleted = false,
                            Price = 50.00m,
                            RegionId = 4,
                            Title = "Сервиз и монтаж на бойлери"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            CityId = 7,
                            CreatedAt = new DateTime(2025, 2, 3, 18, 20, 0, 0, DateTimeKind.Local),
                            CreatorId = "a6f2c4eb-9d8h-4f6g-2f7g-666666666666",
                            Description = "Пълен тест и ремонт на контролни платки за битова и индустриална техника.",
                            ImageUrl = "https://source.unsplash.com/800x450/?circuit-board,repair",
                            IsDeleted = false,
                            Price = 95.00m,
                            RegionId = 5,
                            Title = "Диагностика на електронни табла и управление"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CityId = 1,
                            CreatedAt = new DateTime(2025, 1, 29, 11, 50, 0, 0, DateTimeKind.Local),
                            CreatorId = "c2b8e0a7-5f4d-4b2c-8b3c-222222222222",
                            Description = "Излизане на адрес в рамките на деня за малки ремонти на кухни, печки, хладилници.",
                            ImageUrl = "https://source.unsplash.com/800x450/?home-appliance,repair",
                            IsDeleted = false,
                            Price = 40.00m,
                            RegionId = 1,
                            Title = "Спешен техник за битови уреди (на място)"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CityId = 4,
                            CreatedAt = new DateTime(2025, 1, 12, 15, 5, 0, 0, DateTimeKind.Local),
                            CreatorId = "d3c9f1b8-6a5e-4c3d-9c4d-333333333333",
                            Description = "Професионален монтаж на електрически табла, автомати и защити. Сертифициран електротехник.",
                            ImageUrl = "https://source.unsplash.com/800x450/?electrical-panel,installation",
                            IsDeleted = false,
                            Price = 120.00m,
                            RegionId = 2,
                            Title = "Електрически табла и защити - монтаж"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CityId = 5,
                            CreatedAt = new DateTime(2025, 2, 5, 14, 0, 0, 0, DateTimeKind.Local),
                            CreatorId = "b1a7f9d6-4e3c-4a1b-9a2b-111111111111",
                            Description = "Ремонт на дънни платки и BGA преинсталации (по договаряне).",
                            ImageUrl = "https://source.unsplash.com/800x450/?bga,soldering",
                            IsDeleted = false,
                            Price = 180.00m,
                            RegionId = 3,
                            Title = "Запояване на BGA/микропоколения (усложнена електроника)"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CityId = 6,
                            CreatedAt = new DateTime(2025, 1, 8, 17, 40, 0, 0, DateTimeKind.Local),
                            CreatorId = "e4d0a2c9-7b6f-4d4e-0d5e-444444444444",
                            Description = "Сглобяване на мебели, монтиране на осветителни тела, окабеляване за уреди.",
                            ImageUrl = "https://source.unsplash.com/800x450/?assembly,tools",
                            IsDeleted = false,
                            Price = 30.00m,
                            RegionId = 4,
                            Title = "Монтаж на мебели и електрически елементи"
                        });
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "София-град"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Пловдив"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Варна"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Бургас"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Русе"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Tehnicharche.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Tehnicharche.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tehnicharche.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Tehnicharche.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.City", b =>
                {
                    b.HasOne("Tehnicharche.Data.Models.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.Listing", b =>
                {
                    b.HasOne("Tehnicharche.Data.Models.Category", "Category")
                        .WithMany("Listings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tehnicharche.Data.Models.City", "City")
                        .WithMany("Listings")
                        .HasForeignKey("CityId");

                    b.HasOne("Tehnicharche.Data.Models.ApplicationUser", "Creator")
                        .WithMany("Listings")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tehnicharche.Data.Models.Region", "Region")
                        .WithMany("Listings")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("Creator");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.Category", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.City", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Tehnicharche.Data.Models.Region", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
